<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-FS5UPGRD" failures="3" tests="5" name="masterTest" time="76.121" errors="0" timestamp="2023-03-20T20:21:38 IST">
  <testcase classname="testcases.TC_003ddtLogintest" name="test_login" time="17.411"/>
  <testcase classname="testcases.TC_003ddtLogintest" name="test_login" time="14.225"/>
  <testcase classname="testcases.TC_003ddtLogintest" name="test_login" time="0.381">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testcases.TC_003ddtLogintest.test_login(TC_003ddtLogintest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_login -->
  <testcase classname="testcases.TC_003ddtLogintest" name="test_login" time="0.07">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testcases.TC_003ddtLogintest.test_login(TC_003ddtLogintest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_login -->
  <testcase classname="testcases.TC_003ddtLogintest" name="test_login" time="0.037">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testcases.TC_003ddtLogintest.test_login(TC_003ddtLogintest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_login -->
</testsuite> <!-- masterTest -->
